//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_UPLOAD_STAFFResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_UPLOAD_STAFFResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_UPLOAD_STAFFResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_UPLOAD_STAFFResources.RSP_LM_UPLOAD_STAFFResources_msgrsc", typeof(RSP_LM_UPLOAD_STAFFResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be empty.
        /// </summary>
        internal static string EMPTY_DEPT {
            get {
                return ResourceManager.GetString("EMPTY_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can not be empty.
        /// </summary>
        internal static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender cannot be empty.
        /// </summary>
        internal static string EMPTY_GENDER {
            get {
                return ResourceManager.GetString("EMPTY_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No 1 can not be empty.
        /// </summary>
        internal static string EMPTY_MOBILE_NO {
            get {
                return ResourceManager.GetString("EMPTY_MOBILE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this Inactive Staff, Non Active Date cannot be empty.
        /// </summary>
        internal static string EMPTY_NONACTIVE_DATE {
            get {
                return ResourceManager.GetString("EMPTY_NONACTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position cannot be empty.
        /// </summary>
        internal static string EMPTY_POSITION {
            get {
                return ResourceManager.GetString("EMPTY_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id cannot be empty.
        /// </summary>
        internal static string EMPTY_STAFF_ID {
            get {
                return ResourceManager.GetString("EMPTY_STAFF_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name cannot be empty.
        /// </summary>
        internal static string EMPTY_STAFF_NAME {
            get {
                return ResourceManager.GetString("EMPTY_STAFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be longer than 255 character.
        /// </summary>
        internal static string EXCESS_ADDRESS {
            get {
                return ResourceManager.GetString("EXCESS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_EMAIL {
            get {
                return ResourceManager.GetString("EXCESS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id cannot be longer than 20 character.
        /// </summary>
        internal static string EXCESS_STAFF_ID {
            get {
                return ResourceManager.GetString("EXCESS_STAFF_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name cannot be longer than 100 character.
        /// </summary>
        internal static string EXCESS_STAFF_NAME {
            get {
                return ResourceManager.GetString("EXCESS_STAFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid City.
        /// </summary>
        internal static string INVALID_CITY {
            get {
                return ResourceManager.GetString("INVALID_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country.
        /// </summary>
        internal static string INVALID_COUNTRY {
            get {
                return ResourceManager.GetString("INVALID_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department Code.
        /// </summary>
        internal static string INVALID_DEPT_CODE {
            get {
                return ResourceManager.GetString("INVALID_DEPT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Gender Code.
        /// </summary>
        internal static string INVALID_GENDER {
            get {
                return ResourceManager.GetString("INVALID_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Position.
        /// </summary>
        internal static string INVALID_POSITION {
            get {
                return ResourceManager.GetString("INVALID_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State.
        /// </summary>
        internal static string INVALID_STATE {
            get {
                return ResourceManager.GetString("INVALID_STATE", resourceCulture);
            }
        }
    }
}
