//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_GS_UPLOAD_CASH_BANKResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_GS_UPLOAD_CASH_BANKResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_GS_UPLOAD_CASH_BANKResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_GS_UPLOAD_CASH_BANKResources.RSP_GS_UPLOAD_CASH_BANKResources_msgrsc", typeof(RSP_GS_UPLOAD_CASH_BANKResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS / IS cannot be empty.
        /// </summary>
        internal static string EMPTY_BSIS {
            get {
                return ResourceManager.GetString("EMPTY_BSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit / Credit cannot be empty.
        /// </summary>
        internal static string EMPTY_DBCR {
            get {
                return ResourceManager.GetString("EMPTY_DBCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account cannot be empty.
        /// </summary>
        internal static string EMPTY_GL_ACCOUNT {
            get {
                return ResourceManager.GetString("EMPTY_GL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account cannot be empty.
        /// </summary>
        internal static string EMPTY_GLACCOUNT_NAME {
            get {
                return ResourceManager.GetString("EMPTY_GLACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account No is bigger than 20 Character.
        /// </summary>
        internal static string EXCESS_GL_ACCOUNT {
            get {
                return ResourceManager.GetString("EXCESS_GL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account Name is bigger than 60 Character.
        /// </summary>
        internal static string EXCESS_GLACCOUNT_NAME {
            get {
                return ResourceManager.GetString("EXCESS_GLACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, Active Flag value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BS/IS code, BS/IS value is not B OR I.
        /// </summary>
        internal static string INVALID_BSIS {
            get {
                return ResourceManager.GetString("INVALID_BSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Center Restriction Value, is not 1 / 0.
        /// </summary>
        internal static string INVALID_CENTER_RESTRICT {
            get {
                return ResourceManager.GetString("INVALID_CENTER_RESTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid D/C code, D/C value is not D / C.
        /// </summary>
        internal static string INVALID_DBCR {
            get {
                return ResourceManager.GetString("INVALID_DBCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Restriction Value, is not 1 / 0.
        /// </summary>
        internal static string INVALID_USER_RESTRICT {
            get {
                return ResourceManager.GetString("INVALID_USER_RESTRICT", resourceCulture);
            }
        }
    }
}
