//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_MAINTAIN_STAFFResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_MAINTAIN_STAFFResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_MAINTAIN_STAFFResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_MAINTAIN_STAFFResources.RSP_LM_MAINTAIN_STAFFResources_msgrsc", typeof(RSP_LM_MAINTAIN_STAFFResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _6501 {
            get {
                return ResourceManager.GetString("6501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Staff Id!.
        /// </summary>
        internal static string _6502 {
            get {
                return ResourceManager.GetString("6502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Staff already in used!.
        /// </summary>
        internal static string _6503 {
            get {
                return ResourceManager.GetString("6503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id cannot be empty!.
        /// </summary>
        internal static string _6504 {
            get {
                return ResourceManager.GetString("6504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name cannot be empty!.
        /// </summary>
        internal static string _6505 {
            get {
                return ResourceManager.GetString("6505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _6506 {
            get {
                return ResourceManager.GetString("6506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name cannot be greater than 100 character!.
        /// </summary>
        internal static string _6507 {
            get {
                return ResourceManager.GetString("6507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be empty!.
        /// </summary>
        internal static string _6508 {
            get {
                return ResourceManager.GetString("6508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department!.
        /// </summary>
        internal static string _6509 {
            get {
                return ResourceManager.GetString("6509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Position!.
        /// </summary>
        internal static string _6510 {
            get {
                return ResourceManager.GetString("6510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Supervisor!.
        /// </summary>
        internal static string _6511 {
            get {
                return ResourceManager.GetString("6511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address cannot be empty!.
        /// </summary>
        internal static string _6512 {
            get {
                return ResourceManager.GetString("6512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone 1 cannot be empty!.
        /// </summary>
        internal static string _6513 {
            get {
                return ResourceManager.GetString("6513", resourceCulture);
            }
        }
    }
}
