//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_GS_UPLOAD_GEOGRAPHYResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_GS_UPLOAD_GEOGRAPHYResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_GS_UPLOAD_GEOGRAPHYResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_GS_UPLOAD_GEOGRAPHYResources.RSP_GS_UPLOAD_GEOGRAPHYResources_msgrsc", typeof(RSP_GS_UPLOAD_GEOGRAPHYResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Code cannot be empty.
        /// </summary>
        internal static string EMPTY_GEOGRAPHY_CODE {
            get {
                return ResourceManager.GetString("EMPTY_GEOGRAPHY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Name cannot be empty.
        /// </summary>
        internal static string EMPTY_GEOGRAPHY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_GEOGRAPHY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Code cannot be empty.
        /// </summary>
        internal static string EMPTY_PARENT_CODE {
            get {
                return ResourceManager.GetString("EMPTY_PARENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Code is bigger than 20 character.
        /// </summary>
        internal static string EXCESS_GEOGRAPHY_CODE {
            get {
                return ResourceManager.GetString("EXCESS_GEOGRAPHY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography Name is bigger than 100 character.
        /// </summary>
        internal static string EXCESS_GEOGRAPHY_NAME {
            get {
                return ResourceManager.GetString("EXCESS_GEOGRAPHY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Code is bigger than 20 character.
        /// </summary>
        internal static string EXCESS_PARENT_CODE {
            get {
                return ResourceManager.GetString("EXCESS_PARENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, Active Flag value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent Code.
        /// </summary>
        internal static string INVALID_PARENT_CODE {
            get {
                return ResourceManager.GetString("INVALID_PARENT_CODE", resourceCulture);
            }
        }
    }
}
