//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_MAINTAIN_TENANT_CLASS_GRPResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_MAINTAIN_TENANT_CLASS_GRPResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_MAINTAIN_TENANT_CLASS_GRPResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_MAINTAIN_TENANT_CLASS_GRPResources.RSP_LM_MAINTAIN_TENANT_CLASS_GRPResourc" +
                            "es_msgrsc", typeof(RSP_LM_MAINTAIN_TENANT_CLASS_GRPResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _3701 {
            get {
                return ResourceManager.GetString("3701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Tenant Classification Group Id!.
        /// </summary>
        internal static string _3702 {
            get {
                return ResourceManager.GetString("3702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Tenant Classification Group already in used!.
        /// </summary>
        internal static string _3703 {
            get {
                return ResourceManager.GetString("3703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Classification Group Id cannot be empty!.
        /// </summary>
        internal static string _3704 {
            get {
                return ResourceManager.GetString("3704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Classification Group Name cannot be empty!.
        /// </summary>
        internal static string _3705 {
            get {
                return ResourceManager.GetString("3705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Classification Group Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _3706 {
            get {
                return ResourceManager.GetString("3706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Classification Group Name cannot be greater than 100 character!.
        /// </summary>
        internal static string _3707 {
            get {
                return ResourceManager.GetString("3707", resourceCulture);
            }
        }
    }
}
