//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_ACTIVITY_VALIDITYResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_ACTIVITY_VALIDITYResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_ACTIVITY_VALIDITYResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_ACTIVITY_VALIDITYResources.RSP_ACTIVITY_VALIDITYResources_msgrsc", typeof(RSP_ACTIVITY_VALIDITYResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Code cannot be empty!.
        /// </summary>
        internal static string ERROR001 {
            get {
                return ResourceManager.GetString("ERROR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;&apos;s no activity parameter for this program!.
        /// </summary>
        internal static string ERROR002 {
            get {
                return ResourceManager.GetString("ERROR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id cannot be empty!.
        /// </summary>
        internal static string ERROR003 {
            get {
                return ResourceManager.GetString("ERROR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity is not allowed!.
        /// </summary>
        internal static string ERROR004 {
            get {
                return ResourceManager.GetString("ERROR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Need To Maintain User For This Activity Approval First!.
        /// </summary>
        internal static string ERROR005 {
            get {
                return ResourceManager.GetString("ERROR005", resourceCulture);
            }
        }
    }
}
