//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULEResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULEResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULEResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULEResources.RSP_LM_MAINTAIN_UNIT_TYPE_BILLING" +
                            "_RULEResources_msgrsc", typeof(RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULEResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _6001 {
            get {
                return ResourceManager.GetString("6001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete, Billing Rule already in used!.
        /// </summary>
        internal static string _6002 {
            get {
                return ResourceManager.GetString("6002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Billing Rule Id!.
        /// </summary>
        internal static string _6003 {
            get {
                return ResourceManager.GetString("6003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Id cannot be empty!.
        /// </summary>
        internal static string _6004 {
            get {
                return ResourceManager.GetString("6004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Name cannot be empty!.
        /// </summary>
        internal static string _6005 {
            get {
                return ResourceManager.GetString("6005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _6006 {
            get {
                return ResourceManager.GetString("6006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Name cannot be greater than 100 character!.
        /// </summary>
        internal static string _6007 {
            get {
                return ResourceManager.GetString("6007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Fee charges cannot be empty!.
        /// </summary>
        internal static string _6008 {
            get {
                return ResourceManager.GetString("6008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Booking Fee Chages!.
        /// </summary>
        internal static string _6009 {
            get {
                return ResourceManager.GetString("6009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Percentage cannot be empty!.
        /// </summary>
        internal static string _6010 {
            get {
                return ResourceManager.GetString("6010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Invertal cannot be empty!.
        /// </summary>
        internal static string _6011 {
            get {
                return ResourceManager.GetString("6011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Period Mode cannot be empty!.
        /// </summary>
        internal static string _6012 {
            get {
                return ResourceManager.GetString("6012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Charges Id cannot be empty!.
        /// </summary>
        internal static string _6013 {
            get {
                return ResourceManager.GetString("6013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DP Charges Id!.
        /// </summary>
        internal static string _6014 {
            get {
                return ResourceManager.GetString("6014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment percentage cannot be empty!.
        /// </summary>
        internal static string _6015 {
            get {
                return ResourceManager.GetString("6015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Interval cannot be empty!.
        /// </summary>
        internal static string _6016 {
            get {
                return ResourceManager.GetString("6016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Period Mode cannot be empty!.
        /// </summary>
        internal static string _6017 {
            get {
                return ResourceManager.GetString("6017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Charges Id cannot be empty!.
        /// </summary>
        internal static string _6018 {
            get {
                return ResourceManager.GetString("6018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Installment Charges Id!.
        /// </summary>
        internal static string _6019 {
            get {
                return ResourceManager.GetString("6019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Credit Percentage cannot be empty!.
        /// </summary>
        internal static string _6020 {
            get {
                return ResourceManager.GetString("6020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Credit Interval cannot be empty!.
        /// </summary>
        internal static string _6021 {
            get {
                return ResourceManager.GetString("6021", resourceCulture);
            }
        }
    }
}
