//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_UPLOAD_GSM_CENTERResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_UPLOAD_GSM_CENTERResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_UPLOAD_GSM_CENTERResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_UPLOAD_GSM_CENTERResources.RSP_UPLOAD_GSM_CENTERResources_msgrsc", typeof(RSP_UPLOAD_GSM_CENTERResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code cannot be empty.
        /// </summary>
        internal static string EMPTY_CENTER_CODE {
            get {
                return ResourceManager.GetString("EMPTY_CENTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name cannot be empty.
        /// </summary>
        internal static string EMPTY_CENTER_NAME {
            get {
                return ResourceManager.GetString("EMPTY_CENTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Active Date cannot be empty for this inactive Center.
        /// </summary>
        internal static string EMPTY_NON_ACTIVE_DATE {
            get {
                return ResourceManager.GetString("EMPTY_NON_ACTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code is bigger than 8 character .
        /// </summary>
        internal static string EXCESS_CENTER_CODE {
            get {
                return ResourceManager.GetString("EXCESS_CENTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name is bigger than 80 character.
        /// </summary>
        internal static string EXCESS_CENTER_NAME {
            get {
                return ResourceManager.GetString("EXCESS_CENTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonActiveDate is bigger than 8 character.
        /// </summary>
        internal static string EXCESS_NON_ACTIVE_DATE {
            get {
                return ResourceManager.GetString("EXCESS_NON_ACTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, Active Flag value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
    }
}
