//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_MAINTAIN_TENANTResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_MAINTAIN_TENANTResources_msgsrc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_MAINTAIN_TENANTResources_msgsrc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_MAINTAIN_TENANTResources.RSP_LM_MAINTAIN_TENANTResources_msgsrc", typeof(RSP_LM_MAINTAIN_TENANTResources_msgsrc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _3501 {
            get {
                return ResourceManager.GetString("3501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Tenant Id!.
        /// </summary>
        internal static string _3502 {
            get {
                return ResourceManager.GetString("3502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Tenant already in used.
        /// </summary>
        internal static string _3503 {
            get {
                return ResourceManager.GetString("3503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id cannot be empty!.
        /// </summary>
        internal static string _3504 {
            get {
                return ResourceManager.GetString("3504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name cannot be empty!.
        /// </summary>
        internal static string _3505 {
            get {
                return ResourceManager.GetString("3505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _3506 {
            get {
                return ResourceManager.GetString("3506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name cannot be greater than 100 character!.
        /// </summary>
        internal static string _3507 {
            get {
                return ResourceManager.GetString("3507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty!.
        /// </summary>
        internal static string _3508 {
            get {
                return ResourceManager.GetString("3508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group cannot be empty!.
        /// </summary>
        internal static string _3509 {
            get {
                return ResourceManager.GetString("3509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tenant Group!.
        /// </summary>
        internal static string _3510 {
            get {
                return ResourceManager.GetString("3510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Category cannot be empty!.
        /// </summary>
        internal static string _3511 {
            get {
                return ResourceManager.GetString("3511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tenant Type!.
        /// </summary>
        internal static string _3512 {
            get {
                return ResourceManager.GetString("3512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group cannot be empty!.
        /// </summary>
        internal static string _3513 {
            get {
                return ResourceManager.GetString("3513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Journal Group!.
        /// </summary>
        internal static string _3514 {
            get {
                return ResourceManager.GetString("3514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term cannot be empty!.
        /// </summary>
        internal static string _3515 {
            get {
                return ResourceManager.GetString("3515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Term!.
        /// </summary>
        internal static string _3516 {
            get {
                return ResourceManager.GetString("3516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency cannot be empty!.
        /// </summary>
        internal static string _3517 {
            get {
                return ResourceManager.GetString("3517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Currency!.
        /// </summary>
        internal static string _3518 {
            get {
                return ResourceManager.GetString("3518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman cannot be empty!.
        /// </summary>
        internal static string _3519 {
            get {
                return ResourceManager.GetString("3519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Salesman!.
        /// </summary>
        internal static string _3520 {
            get {
                return ResourceManager.GetString("3520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Business cannot be empty!.
        /// </summary>
        internal static string _3521 {
            get {
                return ResourceManager.GetString("3521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Line of Business!.
        /// </summary>
        internal static string _3522 {
            get {
                return ResourceManager.GetString("3522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tenant Category!.
        /// </summary>
        internal static string _3523 {
            get {
                return ResourceManager.GetString("3523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Type cannot be empty!.
        /// </summary>
        internal static string _3524 {
            get {
                return ResourceManager.GetString("3524", resourceCulture);
            }
        }
    }
}
