//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_UPLOAD_SALESMANResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_UPLOAD_SALESMANResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_UPLOAD_SALESMANResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_UPLOAD_SALESMANResources.RSP_LM_UPLOAD_SALESMANResources_msgrsc", typeof(RSP_LM_UPLOAD_SALESMANResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can not be empty.
        /// </summary>
        internal static string EMPTY_ADDRESS {
            get {
                return ResourceManager.GetString("EMPTY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name can not be empty.
        /// </summary>
        internal static string EMPTY_COMPANY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can not be empty.
        /// </summary>
        internal static string EMPTY_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender cannot be empty.
        /// </summary>
        internal static string EMPTY_GENDER {
            get {
                return ResourceManager.GetString("EMPTY_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No 1 can not be empty.
        /// </summary>
        internal static string EMPTY_MOBILE_PHONE1 {
            get {
                return ResourceManager.GetString("EMPTY_MOBILE_PHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Active Flag = 0, Non Active Date can not be empty.
        /// </summary>
        internal static string EMPTY_NONACTIVE_DATE {
            get {
                return ResourceManager.GetString("EMPTY_NONACTIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Id can not be empty.
        /// </summary>
        internal static string EMPTY_SALESMAN_ID {
            get {
                return ResourceManager.GetString("EMPTY_SALESMAN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Name can not be empty.
        /// </summary>
        internal static string EMPTY_SALESMAN_NAME {
            get {
                return ResourceManager.GetString("EMPTY_SALESMAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Type cannot be empty.
        /// </summary>
        internal static string EMPTY_SALESMANTYPE {
            get {
                return ResourceManager.GetString("EMPTY_SALESMANTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is bigger than 255 Character.
        /// </summary>
        internal static string EXCESS_ADDRESS {
            get {
                return ResourceManager.GetString("EXCESS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EXCESS_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Id is bigger than 8 Character.
        /// </summary>
        internal static string EXCESS_SALESMAN_ID {
            get {
                return ResourceManager.GetString("EXCESS_SALESMAN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Name is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_SALESMAN_NAME {
            get {
                return ResourceManager.GetString("EXCESS_SALESMAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Active Flag, Active Flag value is not 1 / 0.
        /// </summary>
        internal static string INVALID_ACTIVE_FLAG {
            get {
                return ResourceManager.GetString("INVALID_ACTIVE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Gender.
        /// </summary>
        internal static string INVALID_GENDER {
            get {
                return ResourceManager.GetString("INVALID_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Salesman Type.
        /// </summary>
        internal static string INVALID_SALESMANTYPE {
            get {
                return ResourceManager.GetString("INVALID_SALESMANTYPE", resourceCulture);
            }
        }
    }
}
