//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_MAINTAIN_DISCOUNTResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_MAINTAIN_DISCOUNTResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_MAINTAIN_DISCOUNTResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_MAINTAIN_DISCOUNTResources.RSP_LM_MAINTAIN_DISCOUNTResources_msgrsc", typeof(RSP_LM_MAINTAIN_DISCOUNTResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _7001 {
            get {
                return ResourceManager.GetString("7001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Discount Code!.
        /// </summary>
        internal static string _7002 {
            get {
                return ResourceManager.GetString("7002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Discount already in used!.
        /// </summary>
        internal static string _7003 {
            get {
                return ResourceManager.GetString("7003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code cannot be empty!.
        /// </summary>
        internal static string _7004 {
            get {
                return ResourceManager.GetString("7004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name cannot be empty!.
        /// </summary>
        internal static string _7005 {
            get {
                return ResourceManager.GetString("7005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code cannot be greater than 20 character!.
        /// </summary>
        internal static string _7006 {
            get {
                return ResourceManager.GetString("7006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name cannot be greater than 100 character!.
        /// </summary>
        internal static string _7007 {
            get {
                return ResourceManager.GetString("7007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type cannot be empty!.
        /// </summary>
        internal static string _7008 {
            get {
                return ResourceManager.GetString("7008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Type!.
        /// </summary>
        internal static string _7009 {
            get {
                return ResourceManager.GetString("7009", resourceCulture);
            }
        }
    }
}
