//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM05500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM05500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM05500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM05500FrontResources.GSM05500FrontResources_msgrsc", typeof(GSM05500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string BS_CRNC {
            get {
                return ResourceManager.GetString("BS_CRNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Curr. Base Rate.
        /// </summary>
        internal static string BS_CRNC_BS_RT {
            get {
                return ResourceManager.GetString("BS_CRNC_BS_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate.
        /// </summary>
        internal static string BS_CRNC_RT {
            get {
                return ResourceManager.GetString("BS_CRNC_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string CRNC_CD {
            get {
                return ResourceManager.GetString("CRNC_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string CRNC_NM {
            get {
                return ResourceManager.GetString("CRNC_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string CRNC_RT {
            get {
                return ResourceManager.GetString("CRNC_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CRT_BY {
            get {
                return ResourceManager.GetString("CRT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string CRT_DT {
            get {
                return ResourceManager.GetString("CRT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string LC_CRNC {
            get {
                return ResourceManager.GetString("LC_CRNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Curr. Base Rate.
        /// </summary>
        internal static string LC_CRNC_BS_RT {
            get {
                return ResourceManager.GetString("LC_CRNC_BS_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate.
        /// </summary>
        internal static string LC_CRNC_RT {
            get {
                return ResourceManager.GetString("LC_CRNC_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate type.
        /// </summary>
        internal static string RATE_TYP {
            get {
                return ResourceManager.GetString("RATE_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Date.
        /// </summary>
        internal static string RT_DT {
            get {
                return ResourceManager.GetString("RT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type.
        /// </summary>
        internal static string RT_TYP {
            get {
                return ResourceManager.GetString("RT_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Code.
        /// </summary>
        internal static string RT_TYP_CD {
            get {
                return ResourceManager.GetString("RT_TYP_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Name.
        /// </summary>
        internal static string RT_TYP_NM {
            get {
                return ResourceManager.GetString("RT_TYP_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        internal static string UPDT_BY {
            get {
                return ResourceManager.GetString("UPDT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string UPDT_DT {
            get {
                return ResourceManager.GetString("UPDT_DT", resourceCulture);
            }
        }
    }
}
