//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_GS_MAINTAIN_BUILDING_FLOORResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_GS_MAINTAIN_BUILDING_FLOORResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_GS_MAINTAIN_BUILDING_FLOORResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_GS_MAINTAIN_BUILDING_FLOORResources.RSP_GS_MAINTAIN_BUILDING_FLOORResources_m" +
                            "sgrsc", typeof(RSP_GS_MAINTAIN_BUILDING_FLOORResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error process, please contact your administrator!.
        /// </summary>
        internal static string _2541 {
            get {
                return ResourceManager.GetString("2541", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Floor Id!.
        /// </summary>
        internal static string _2542 {
            get {
                return ResourceManager.GetString("2542", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete, Floor already in used!.
        /// </summary>
        internal static string _2543 {
            get {
                return ResourceManager.GetString("2543", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Id cannot be empty!.
        /// </summary>
        internal static string _2544 {
            get {
                return ResourceManager.GetString("2544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Name cannot be empty!.
        /// </summary>
        internal static string _2545 {
            get {
                return ResourceManager.GetString("2545", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _2546 {
            get {
                return ResourceManager.GetString("2546", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Id cannot be greater than 20 character!.
        /// </summary>
        internal static string _2547 {
            get {
                return ResourceManager.GetString("2547", resourceCulture);
            }
        }
    }
}
