//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM10500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM10500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM10500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM10500FrontResources.GSM10500FrontResources_msgrsc", typeof(GSM10500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Code.
        /// </summary>
        internal static string AGN_CD {
            get {
                return ResourceManager.GetString("AGN_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Name.
        /// </summary>
        internal static string AGN_NM {
            get {
                return ResourceManager.GetString("AGN_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Coloumn Detail.
        /// </summary>
        internal static string AGNG_CLMN_DT {
            get {
                return ResourceManager.GetString("AGNG_CLMN_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloumn Name.
        /// </summary>
        internal static string CLMN_NO {
            get {
                return ResourceManager.GetString("CLMN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CRT_BY {
            get {
                return ResourceManager.GetString("CRT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string CRT_DT {
            get {
                return ResourceManager.GetString("CRT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Point.
        /// </summary>
        internal static string DCML_PNT {
            get {
                return ResourceManager.GetString("DCML_PNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit Length.
        /// </summary>
        internal static string DGT_LNGHT {
            get {
                return ResourceManager.GetString("DGT_LNGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Days.
        /// </summary>
        internal static string FRM_DYS {
            get {
                return ResourceManager.GetString("FRM_DYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding Mode.
        /// </summary>
        internal static string RND_MD {
            get {
                return ResourceManager.GetString("RND_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding Unit.
        /// </summary>
        internal static string RND_UNT {
            get {
                return ResourceManager.GetString("RND_UNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Days.
        /// </summary>
        internal static string TO_DYS {
            get {
                return ResourceManager.GetString("TO_DYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string UPDT_BY {
            get {
                return ResourceManager.GetString("UPDT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string UPDT_DT {
            get {
                return ResourceManager.GetString("UPDT_DT", resourceCulture);
            }
        }
    }
}
