//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM00700FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LookupAPFrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupAPFrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LookupAPFrontResources.LookupAPFrontResources_msgrsc", typeof(LookupAPFrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string ACCNT_NO {
            get {
                return ResourceManager.GetString("ACCNT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ADDRS {
            get {
                return ResourceManager.GetString("ADDRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID.
        /// </summary>
        internal static string ALLOC_ID {
            get {
                return ResourceManager.GetString("ALLOC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name.
        /// </summary>
        internal static string ALLOC_NM {
            get {
                return ResourceManager.GetString("ALLOC_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Name.
        /// </summary>
        internal static string ALS_NM {
            get {
                return ResourceManager.GetString("ALS_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CNCL {
            get {
                return ResourceManager.GetString("CNCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CTGRY {
            get {
                return ResourceManager.GetString("CTGRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string CURR {
            get {
                return ResourceManager.GetString("CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string DCMNT_DATE {
            get {
                return ResourceManager.GetString("DCMNT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string DCMNT_NO {
            get {
                return ResourceManager.GetString("DCMNT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept..
        /// </summary>
        internal static string DEPT {
            get {
                return ResourceManager.GetString("DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept. Mode.
        /// </summary>
        internal static string DEPT_MD {
            get {
                return ResourceManager.GetString("DEPT_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DUE_DATE {
            get {
                return ResourceManager.GetString("DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure ID.
        /// </summary>
        internal static string EXPN_ID {
            get {
                return ResourceManager.GetString("EXPN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Name.
        /// </summary>
        internal static string EXPN_NM {
            get {
                return ResourceManager.GetString("EXPN_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string PRDCT_ID {
            get {
                return ResourceManager.GetString("PRDCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string PRDCT_NM {
            get {
                return ResourceManager.GetString("PRDCT_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string RFRNCE {
            get {
                return ResourceManager.GetString("RFRNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date.
        /// </summary>
        internal static string RFRNCE_DT {
            get {
                return ResourceManager.GetString("RFRNCE_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RFSH {
            get {
                return ResourceManager.GetString("RFSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        internal static string RMN_AMNT {
            get {
                return ResourceManager.GetString("RMN_AMNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq. No.
        /// </summary>
        internal static string SEQ_NO {
            get {
                return ResourceManager.GetString("SEQ_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string SHW_ALL {
            get {
                return ResourceManager.GetString("SHW_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string SPLR {
            get {
                return ResourceManager.GetString("SPLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        internal static string SPR_ID {
            get {
                return ResourceManager.GetString("SPR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string SPR_NM {
            get {
                return ResourceManager.GetString("SPR_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SRCH {
            get {
                return ResourceManager.GetString("SRCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Able.
        /// </summary>
        internal static string TXBLE {
            get {
                return ResourceManager.GetString("TXBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UNIT {
            get {
                return ResourceManager.GetString("UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax.
        /// </summary>
        internal static string WTH_TAX {
            get {
                return ResourceManager.GetString("WTH_TAX", resourceCulture);
            }
        }
    }
}
