//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_LM_UPLOAD_TENANTResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_LM_UPLOAD_TENANTResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_LM_UPLOAD_TENANTResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_LM_UPLOAD_TENANTResources.RSP_LM_UPLOAD_TENANTResources_msgrsc", typeof(RSP_LM_UPLOAD_TENANTResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can not be empty.
        /// </summary>
        internal static string EMPTY_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No 1 can not be empty.
        /// </summary>
        internal static string EMPTY_PHONE1 {
            get {
                return ResourceManager.GetString("EMPTY_PHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Id can not be empty.
        /// </summary>
        internal static string EMPTY_TENANT_ID {
            get {
                return ResourceManager.GetString("EMPTY_TENANT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Name can not be empty.
        /// </summary>
        internal static string EMPTY_TENANT_NAME {
            get {
                return ResourceManager.GetString("EMPTY_TENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EXCESS_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Id is bigger than 20 Character.
        /// </summary>
        internal static string EXCESS_TENANT_ID {
            get {
                return ResourceManager.GetString("EXCESS_TENANT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Name is bigger than 100 Character.
        /// </summary>
        internal static string EXCESS_TENANT_NAME {
            get {
                return ResourceManager.GetString("EXCESS_TENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Currency.
        /// </summary>
        internal static string INVALID_CURRENCY {
            get {
                return ResourceManager.GetString("INVALID_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Journal Group.
        /// </summary>
        internal static string INVALID_JOURNAL_GROUP {
            get {
                return ResourceManager.GetString("INVALID_JOURNAL_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Line of Business.
        /// </summary>
        internal static string INVALID_LOB {
            get {
                return ResourceManager.GetString("INVALID_LOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Term.
        /// </summary>
        internal static string INVALID_PAYMENT_TERM {
            get {
                return ResourceManager.GetString("INVALID_PAYMENT_TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Salesman.
        /// </summary>
        internal static string INVALID_SALESMAN {
            get {
                return ResourceManager.GetString("INVALID_SALESMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} Category.
        /// </summary>
        internal static string INVALID_TENANT_CATEGORY {
            get {
                return ResourceManager.GetString("INVALID_TENANT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} Group.
        /// </summary>
        internal static string INVALID_TENANT_GROUP {
            get {
                return ResourceManager.GetString("INVALID_TENANT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tenant Type.
        /// </summary>
        internal static string INVALID_TENANT_TYPE {
            get {
                return ResourceManager.GetString("INVALID TENANT TYPE", resourceCulture);
            }
        }
    }
}
