//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMI00100FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM02000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM02000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM02000FrontResources.LMM02000FrontResources_msgrsc", typeof(LMM02000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ADDRS {
            get {
                return ResourceManager.GetString("ADDRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CMPN_NM {
            get {
                return ResourceManager.GetString("CMPN_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        internal static string CRT_BY {
            get {
                return ResourceManager.GetString("CRT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string CRT_DT {
            get {
                return ResourceManager.GetString("CRT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EML_ADDRS {
            get {
                return ResourceManager.GetString("EML_ADDRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string MB_PHNE {
            get {
                return ResourceManager.GetString("MB_PHNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIK.
        /// </summary>
        internal static string NIK {
            get {
                return ResourceManager.GetString("NIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string PRTY {
            get {
                return ResourceManager.GetString("PRTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman ID.
        /// </summary>
        internal static string SLSMN_ID {
            get {
                return ResourceManager.GetString("SLSMN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Name.
        /// </summary>
        internal static string SLSMN_NM {
            get {
                return ResourceManager.GetString("SLSMN_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Type.
        /// </summary>
        internal static string SLSMN_TYP {
            get {
                return ResourceManager.GetString("SLSMN_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string TMPLT {
            get {
                return ResourceManager.GetString("TMPLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string UPDT_BY {
            get {
                return ResourceManager.GetString("UPDT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string UPDT_DT {
            get {
                return ResourceManager.GetString("UPDT_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UPLD {
            get {
                return ResourceManager.GetString("UPLD", resourceCulture);
            }
        }
    }
}
